### PR TITLE
kubi's v0.16.0 signed and unsigned sigs

### PR DESCRIPTION
**Pull request by iamkubi**

### CODE REVIEW

**Comment by thrasher-** [comment]
Thanks! Unsigned sigs match: https://github.com/litecoin-project/gitian.sigs.ltc/pull/110

**Comment by iamkubi** [comment]
Updated with signed signatures.

**Comment by thrasher-** [comment]
It appears that the signed sigs for both windows and linux mismatch compared to the other v0.16.0 PR's since they are the same hashes of the previous v0.16.0rc1 signed gitian builds.

**Comment by thrasher-** [comment]
No worries!

**Comment by iamkubi** [comment]
Should be fixed now.

**Comment by thrasher-** [comment]
Sigs match, thanks!

**Pull request merged**
